### ISSUE TITLE
Add a cibuildwheel test step - to verify the wheels can be installed and used

### ISSUE THREAD

**Issue by adamserafini** [joerick/python-abi3-package-sample#14]
fyi: I'm trying to use this recipe in my own project and finding I get this error in my CI for the mac osx abi3 build, but only when I try and test/install it:

https://github.com/adamserafini/zaml/actions/runs/4242743620/jobs/7374627494
```
ERROR: zaml-0.0.8-cp36-abi3-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

I'm not asking to fix that bug or get support here, but I do think it would be good to add a 'test' step to the `cibuildwheel` config as a sort of 'proof' that this approach definitely works.

Happy to add one btw. if this proposal is likely to be accepted.

**Comment by joerick** [comment]
I beleive this isn't an issue with the `abi3` bit, but actually the `macosx_11_0`. 

This is [an issue with pip](https://github.com/pypa/pip/issues/11789)/macOS, where older pythons think they're on 10.16, rather than the actual version. See this issue for more info - https://github.com/pypa/cibuildwheel/issues/1410

You might be able to get the build to work by setting `SYSTEM_VERSION_COMPAT=0` during the build/test. However, Python 3.6 users are unlikely to be able to use the wheels either, without that flag. Perhaps you could reduce the macos minimum version?

**Comment by adamserafini** [comment]
🙇 OK, thanks a lot for the hint. I will investigate that.

I do agree it cannot be about `abi3`, because I added this to `pyproject.toml` and it passes fine!

```
[tool.cibuildwheel]
test-command = "python -c 'import spam; spam.system(\"exit 0\")'"
```
